services:
  plausible_db:
    image: postgres:16-alpine
    container_name: plausible_db
    restart: always
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=plausible_db
    networks:
      - app-network

  plausible_events_db:
    image: clickhouse/clickhouse-server:24.3-alpine
    container_name: plausible_events_db
    restart: always
    volumes:
      - ./event-data:/var/lib/clickhouse
      - ./clickhouse/clickhouse-config.xml:/etc/clickhouse-server/config.d/logging.xml:ro
      - ./clickhouse/clickhouse-user-config.xml:/etc/clickhouse-server/users.d/logging.xml:ro
    environment:
      - CLICKHOUSE_DB=plausible_events_db
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - app-network

  plausible:
    image: ghcr.io/plausible/community-edition:latest
    container_name: plausible_app
    restart: always
    depends_on:
      - plausible_db
      - plausible_events_db
    environment:
      - BASE_URL=https://analytics.rubenjakob.com
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - TOTP_VAULT_KEY=${TOTP_VAULT_KEY}
      - DATABASE_URL=postgres://postgres:${POSTGRES_PASSWORD}@plausible_db:5432/plausible_db
      - CLICKHOUSE_DATABASE_URL=http://plausible_events_db:8123/plausible_events_db
    networks:
      - app-network

networks:
  app-network:
    external: true
